name=PCFKeypad
version=1.0.0
author=Sergey Nikolaevich <gray_wolf19@mail.ru>
maintainer=Sergey Nikolaevich <gray_wolf19@mail.ru>
sentence=Keypad 4x4 driver for PCF8574 I2C expander.
paragraph=Supports debouncing, auto-repeat, power save, ghosting protection, interrupt handling.
category=Device Control
url=https://github.com/klenov1900-lang/PCFKeypad
architectures=*
includes=PCFKeypad.h
